name: CMake FeBundle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cpp_compiler: g++
            build_type: Release
          - os: ubuntu-latest
            cpp_compiler: clang++
            build_type: Release
          - os: windows-latest
            cpp_compiler: cl
            build_type: Release

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive


      - name: Install SDL deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake ninja-build \
            libasound2-dev libpulse-dev libaudio-dev \
            libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev \
            libxi-dev libxss-dev libwayland-dev libxkbcommon-dev libdrm-dev \
            libgbm-dev libgl1-mesa-dev libvulkan-dev

      - name: Build SDL3 (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake build-essential
          git clone https://github.com/libsdl-org/SDL.git --branch main --depth 1
          cmake -S SDL -B SDL/build -DCMAKE_INSTALL_PREFIX=/usr
          sudo cmake --build SDL/build --target install

      - name: Build SDL3_image (Linux)
        if: runner.os == 'Linux'
        run: |
          git clone https://github.com/libsdl-org/SDL_image.git --branch main --depth 1
          cmake -S SDL_image -B SDL_image/build -DCMAKE_INSTALL_PREFIX=/usr
          sudo cmake --build SDL_image/build --target install

      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1


      - name: Setup vcpkg (Windows)
        if: runner.os == 'Windows'
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgArguments: 'sdl3 sdl3-image'
          vcpkgGitCommitId: 'latest'
          vcpkgDirectory: '${{ runner.temp }}/vcpkg'

      - name: Install Ninja (Windows)
        if: runner.os == 'Windows'
        run: choco install ninja -y

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"


      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -G Ninja
          -DCMAKE_TOOLCHAIN_FILE=${{ runner.temp }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          -S ${{ github.workspace }}


      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Run Unit Tests (Linux)
        if: runner.os == 'Linux'
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ./tests/fe_bundle_unit_tests

      - name: Run Unit Tests (Windows)
        if: runner.os == 'Windows'
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: .\tests\fe_bundle_unit_tests.exe
