name: CMake FeBundle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cpp_compiler: g++
            build_type: Release
          - os: ubuntu-latest
            cpp_compiler: clang++
            build_type: Release
          - os: windows-latest
            cpp_compiler: cl
            build_type: Release

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl3-dev libsdl3-image-dev ninja-build

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install ninja -y

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -G Ninja
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Run Unit Tests
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: |
          echo "Running FeBundle unit tests..."
          ./tests/fe_bundle_unit_tests || exit 1
